"""add guest_id to VideoJob

Revision ID: 3daa464ca080
Revises: de82dbffc36c
Create Date: 2026-05-17 18:55:18.154480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3daa464ca080'
down_revision = 'de82dbffc36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_video_job_guest_id'), ['guest_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_job_guest_id'))
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###
