"""empty message

Revision ID: 42d8ac56c8c8
Revises: d5b1169acbf9
Create Date: 2026-02-15 15:03:37.725026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d8ac56c8c8'
down_revision = 'd5b1169acbf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))
        batch_op.drop_column('tokens')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))
        batch_op.drop_column('daily_limit')

    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_charged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.drop_column('usage_charged')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_limit', sa.INTEGER(), nullable=True))
        batch_op.drop_column('plan')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens', sa.INTEGER(), nullable=False))
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
