"""empty message

Revision ID: 54a6344f4475
Revises: 526f9a5c2fab
Create Date: 2026-02-11 13:44:03.375347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a6344f4475'
down_revision = '526f9a5c2fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_tokens', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.drop_column('required_tokens')

    # ### end Alembic commands ###
