"""empty message

Revision ID: 57ef13de2929
Revises: 95582547e897
Create Date: 2026-02-18 23:05:25.623630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ef13de2929'
down_revision = '95582547e897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.drop_column('transcript_data')

    # ### end Alembic commands ###
