"""empty message

Revision ID: 624e88b59efc
Revises: f97a2434a7cc
Create Date: 2026-02-17 23:05:09.608209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624e88b59efc'
down_revision = 'f97a2434a7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clips_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.drop_column('clips_data')

    # ### end Alembic commands ###
