"""empty message

Revision ID: d5b1169acbf9
Revises: 54a6344f4475
Create Date: 2026-02-15 14:21:44.757415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b1169acbf9'
down_revision = '54a6344f4475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used_today', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_reset', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_reset')
        batch_op.drop_column('used_today')
        batch_op.drop_column('daily_limit')

    # ### end Alembic commands ###
