"""empty message

Revision ID: d60a3474dc97
Revises: a16c3362d4a5
Create Date: 2026-02-16 20:30:31.993061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60a3474dc97'
down_revision = 'a16c3362d4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aspect_ratio', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.drop_column('aspect_ratio')

    # ### end Alembic commands ###
