"""empty message

Revision ID: d99639987ac4
Revises: 4f2dd58c9dde
Create Date: 2026-02-05 03:43:31.088753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99639987ac4'
down_revision = '4f2dd58c9dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
