"""add 30 cycle

Revision ID: de82dbffc36c
Revises: de5da58934b0
Create Date: 2026-04-24 21:30:11.013425

"""
from alembic import op
import sqlalchemy as sa
import datetime

# revision identifiers, used by Alembic.
revision = 'de82dbffc36c'
down_revision = 'de5da58934b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'subscription_start',
                sa.Date(),
                nullable=False,
                server_default=sa.text("'2024-01-01'")
            )
        )
        batch_op.add_column(sa.Column('used_this_cycle', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('used_this_cycle')
        batch_op.drop_column('subscription_start')

    # ### end Alembic commands ###
