"""empty message

Revision ID: f97a2434a7cc
Revises: d60a3474dc97
Create Date: 2026-02-17 20:01:11.653471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97a2434a7cc'
down_revision = 'd60a3474dc97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_job', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_file')

    # ### end Alembic commands ###
